CREATE TABLE IF NOT EXISTS biodata(
  id BIGSERIAL PRIMARY KEY,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(30),
  dob VARCHAR(10) NOT NULL,
  pob VARCHAR(50) NOT NULL,
  address VARCHAR(255) NOT NULL,
  martial_status BOOLEAN NOT NULL
);
CREATE TABLE IF NOT EXISTS employees(
  id BIGSERIAL PRIMARY KEY,
  biodata_id BIGINT NOT NULL UNIQUE REFERENCES employees(id) ON DELETE CASCADE,
  nip VARCHAR(5) NOT NULL UNIQUE,
  status VARCHAR(10) NOT NULL,
  salary NUMERIC(10) NOT NULL
);
CREATE TABLE IF NOT EXISTS contact_persons(
  id BIGSERIAL PRIMARY KEY,
  biodata_id BIGINT NOT NULL REFERENCES biodata(id) ON DELETE CASCADE,
  type VARCHAR(5) NOT NULL,
  contact VARCHAR(50)
);
CREATE TABLE IF NOT EXISTS employee_leaves(
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  periode VARCHAR(4) NOT NULL,
  regular_quota INT NOT NULL
);
CREATE TABLE IF NOT EXISTS leaves(
  id BIGSERIAL PRIMARY KEY,
  type VARCHAR(10) NOT NULL,
  name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS leave_requests(
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  leave_id BIGINT NOT NULL REFERENCES leaves(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS families(
  id BIGSERIAL PRIMARY KEY,
  biodata_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  name VARCHAR(100) NOT NULL,
  status VARCHAR(50) NOT NULL
);
CREATE TABLE IF NOT EXISTS positions(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL
);
CREATE TABLE IF NOT EXISTS employee_positions(
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  position_id BIGINT NOT NULL REFERENCES positions(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS travel_types(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  travel_fee INT NOT NULL
);
CREATE TABLE IF NOT EXISTS travel_requests(
  id BIGSERIAL PRIMARY KEY,
  employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  travel_type_id BIGINT NOT NULL REFERENCES travel_types(id) ON DELETE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL
);
CREATE TABLE IF NOT EXISTS travel_settlements(
  id BIGSERIAL PRIMARY KEY,
  travel_request_id BIGINT NOT NULL REFERENCES travel_requests(id) ON DELETE CASCADE,
  item_name VARCHAR(100) NOT NULL,
  item_cost INT NOT NULL
);
CREATE TABLE IF NOT EXISTS departments(
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);